spring:
  application:
    name: api-gateway-zuul

server: 
  port: 1101
  
zuul:
  routes:
# single-instance
     eureka-client:
       path: /eureka-client/**
       url: http://localhost:8002/
# multi-instance
     api-b:
        path: /api-b/**
        serviceId: api-b
            
api-b:
  ribbon:
    listOfServers: http://localhost:8101/,http://localhost:8002/       
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/